/**
 * @overview Hook for fetching calendar events.
 *
 * Copyright © 2021-2026 Hoagie Club and affiliates.
 */

import type { CalendarEvent } from '@/types';

const y = new Date().getFullYear();
const m = new Date().getMonth();

const d = (day: number, hour: number, min = 0) => new Date(y, m, day, hour, min).toISOString();

const allDay = (day: number) => ({
	start: new Date(y, m, day, 0, 0).toISOString(),
	end: new Date(y, m, day, 23, 59).toISOString(),
});

const now = new Date();
const sunday = new Date(now);
sunday.setDate(now.getDate() - now.getDay());
const SUN = sunday.getDate();
const MON = SUN + 1;
const TUE = SUN + 2;
const WED = SUN + 3;
const THU = SUN + 4;
const FRI = SUN + 5;
const SAT = SUN + 6;

const PLACEHOLDER_EVENTS: CalendarEvent[] = [
	// ── All-day events ──
	{
		id: 'a1',
		name: 'Campus Pickup Basketball',
		...allDay(MON),
		location: 'Dillon Gym',
		description: '',
		host: 'Athletics',
		owner: '',
		category: 'sports',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'a2',
		name: 'Thesis Chapter 2 Due',
		...allDay(TUE),
		location: 'Online',
		description: '',
		host: 'Academic Affairs',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'a3',
		name: 'Preview Day',
		...allDay(WED),
		location: 'Campus',
		description: '',
		host: 'Admissions',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'a4',
		name: 'Housing Application Due',
		...allDay(THU),
		location: 'Online',
		description: '',
		host: 'Housing Office',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'a5',
		name: 'TigerApps Spring Project',
		...allDay(FRI),
		location: 'Friend Center',
		description: '',
		host: 'TigerApps',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},

	// ── Sunday ──
	{
		id: 's1',
		name: 'Acapella Group Rehearsal',
		start: d(SUN, 10),
		end: d(SUN, 12),
		location: 'Richardson Auditorium',
		description: '',
		host: 'Acapella',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 's2',
		name: 'Free Bagels',
		start: d(SUN, 11),
		end: d(SUN, 12),
		location: 'CS Building',
		description: '',
		host: 'CS Dept',
		owner: '',
		category: 'food',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 's3',
		name: 'Sunday Movie Night',
		start: d(SUN, 19),
		end: d(SUN, 22),
		location: 'Whitman Common Room',
		description: '',
		host: 'Whitman',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},

	// ── Monday ──
	{
		id: 'm1',
		name: 'Women in CS',
		start: d(MON, 9),
		end: d(MON, 10),
		location: 'Friend 101',
		description: '',
		host: 'CS Dept',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'm2',
		name: 'BSU Weekly Meeting',
		start: d(MON, 10),
		end: d(MON, 11),
		location: '3rd Floor Frist',
		description: '',
		host: 'BSU',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'm3',
		name: 'Environ. Justice',
		start: d(MON, 10, 30),
		end: d(MON, 12),
		location: 'Robertson Hall',
		description: '',
		host: 'Env. Club',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'm4',
		name: 'Free Boba',
		start: d(MON, 13),
		end: d(MON, 14),
		location: 'Frist Campus Center',
		description: '',
		host: 'Student Gov',
		owner: '',
		category: 'food',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'm5',
		name: 'Mock Interview',
		start: d(MON, 16),
		end: d(MON, 18),
		location: 'Career Services',
		description: '',
		host: 'Career Services',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'm6',
		name: 'Triangle Club',
		start: d(MON, 16, 30),
		end: d(MON, 19),
		location: 'E-Quad',
		description: '',
		host: 'Triangle',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'm7',
		name: 'Daily Princetonian',
		start: d(MON, 20),
		end: d(MON, 21, 30),
		location: 'Newsroom',
		description: '',
		host: 'Daily Prince',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},

	// ── Tuesday ──
	{
		id: 't1',
		name: 'Investment Banking Info',
		start: d(TUE, 10),
		end: d(TUE, 11),
		location: 'Robertson Hall',
		description: '',
		host: 'Finance Club',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 't2',
		name: 'Mental Health Workshop',
		start: d(TUE, 11),
		end: d(TUE, 12, 30),
		location: 'McCosh Health',
		description: '',
		host: 'UHS',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 't3',
		name: 'Physical Study Group',
		start: d(TUE, 13, 15),
		end: d(TUE, 15),
		location: 'Jadwin Hall',
		description: '',
		host: 'Physics Dept',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 't4',
		name: 'AI at Princeton',
		start: d(TUE, 16),
		end: d(TUE, 18),
		location: 'CS Building',
		description: '',
		host: 'AI Lab',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 't5',
		name: 'HackPrinceton Info',
		start: d(TUE, 17),
		end: d(TUE, 19),
		location: 'Friend Center',
		description: '',
		host: 'HackPrinceton',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 't6',
		name: 'Nassau Opry',
		start: d(TUE, 20),
		end: d(TUE, 22),
		location: 'McCarter Theatre',
		description: '',
		host: 'Arts Council',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},

	// ── Wednesday ──
	{
		id: 'w1',
		name: 'Model UN',
		start: d(WED, 10),
		end: d(WED, 12),
		location: 'Robertson Hall',
		description: '',
		host: 'Model UN',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'w2',
		name: 'Campus YM',
		start: d(WED, 10),
		end: d(WED, 11, 30),
		location: 'Murray-Dodge',
		description: '',
		host: 'CampusYM',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'w3',
		name: 'Debate Club',
		start: d(WED, 10, 30),
		end: d(WED, 12),
		location: 'East Pyne',
		description: '',
		host: 'Debate Club',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'w4',
		name: 'Quantum Computing',
		start: d(WED, 13),
		end: d(WED, 14, 30),
		location: 'Friend 101',
		description: '',
		host: 'CS Dept',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'w5',
		name: 'African Students Assoc.',
		start: d(WED, 15, 30),
		end: d(WED, 17),
		location: 'Carl Icahn Lab',
		description: '',
		host: 'PASA',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'w6',
		name: 'Princeton Internl.',
		start: d(WED, 16),
		end: d(WED, 18),
		location: 'Prospect House',
		description: '',
		host: 'Intl. Students',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'w7',
		name: 'Take-Back Night',
		start: d(WED, 19),
		end: d(WED, 21),
		location: 'Frist Campus Center',
		description: '',
		host: 'Student Gov',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'w8',
		name: 'Free Pizza',
		start: d(WED, 12),
		end: d(WED, 13),
		location: 'CS Building Lobby',
		description: '',
		host: 'CS Dept',
		owner: '',
		category: 'food',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'w9',
		name: 'diSiac Dance Co.',
		start: d(WED, 20),
		end: d(WED, 22),
		location: 'Dillon Studio',
		description: '',
		host: 'diSiac',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},

	// ── Thursday ──
	{
		id: 'th1',
		name: 'Dance Team Practice',
		start: d(THU, 10),
		end: d(THU, 12),
		location: 'Dillon Studio',
		description: '',
		host: 'Dance Team',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'th2',
		name: 'CS Junior Seminar',
		start: d(THU, 10),
		end: d(THU, 12),
		location: 'Friend 101',
		description: '',
		host: 'CS Dept',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'th3',
		name: 'Volleyball Practice',
		start: d(THU, 10, 30),
		end: d(THU, 12, 30),
		location: 'Dillon Gym',
		description: '',
		host: 'Athletics',
		owner: '',
		category: 'sports',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'th4',
		name: 'Finance Club Meeting',
		start: d(THU, 11),
		end: d(THU, 12, 30),
		location: 'Robertson Hall',
		description: '',
		host: 'Finance Club',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'th5',
		name: 'Free Lunch',
		start: d(THU, 12),
		end: d(THU, 13),
		location: 'Whitman Dining',
		description: '',
		host: 'Whitman College',
		owner: '',
		category: 'food',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'th6',
		name: 'Robotics Club',
		start: d(THU, 14),
		end: d(THU, 16),
		location: 'Engineering Quad',
		description: '',
		host: 'Robotics Club',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'th7',
		name: 'Music Ensemble',
		start: d(THU, 14),
		end: d(THU, 16),
		location: 'Woolworth Center',
		description: '',
		host: 'Music Dept',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'th8',
		name: 'Whig-Clio Debate',
		start: d(THU, 14, 30),
		end: d(THU, 16, 30),
		location: 'Whig Hall',
		description: '',
		host: 'Whig-Clio',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'th9',
		name: 'Rocky Formal Planning',
		start: d(THU, 15),
		end: d(THU, 17),
		location: 'Rocky Common Room',
		description: '',
		host: 'Rocky College',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'th10',
		name: 'Senior Thesis Concert',
		start: d(THU, 19),
		end: d(THU, 21),
		location: 'Richardson Auditorium',
		description: '',
		host: 'Music Dept',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'th11',
		name: 'Chess Club',
		start: d(THU, 19),
		end: d(THU, 21),
		location: 'Marx Hall',
		description: '',
		host: 'Chess Club',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'th12',
		name: 'Hack Princeton',
		start: d(THU, 20),
		end: d(THU, 23, 59),
		location: 'Friend Center',
		description: '',
		host: 'HackPrinceton',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},

	// ── Friday ──
	{
		id: 'f1',
		name: 'Chemistry Lab',
		start: d(FRI, 9),
		end: d(FRI, 12),
		location: 'Frick Chemistry',
		description: '',
		host: 'Chemistry Dept',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'f2',
		name: 'Rocky Formal',
		start: d(FRI, 10),
		end: d(FRI, 12),
		location: 'Rocky Common Room',
		description: '',
		host: 'Rocky College',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'f3',
		name: 'Hack Princeton Check-in',
		start: d(FRI, 10, 30),
		end: d(FRI, 13),
		location: 'Friend Center',
		description: '',
		host: 'HackPrinceton',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'f4',
		name: 'Free Food at Whitman',
		start: d(FRI, 13),
		end: d(FRI, 14),
		location: 'Whitman Dining',
		description: '',
		host: 'Whitman College',
		owner: '',
		category: 'food',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'f5',
		name: 'Film Club Screening',
		start: d(FRI, 15),
		end: d(FRI, 18),
		location: 'McCosh 50',
		description: '',
		host: 'Film Club',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'f6',
		name: 'Fringe Festival',
		start: d(FRI, 15),
		end: d(FRI, 18),
		location: 'Lewis Center',
		description: '',
		host: 'Arts Council',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'f7',
		name: 'Robotics Showcase',
		start: d(FRI, 15, 30),
		end: d(FRI, 17),
		location: 'E-Quad',
		description: '',
		host: 'Robotics Club',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'f8',
		name: 'eSports Tourney',
		start: d(FRI, 16),
		end: d(FRI, 20),
		location: 'Frist Gaming',
		description: '',
		host: 'eSports Club',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'f9',
		name: 'Hack Prize Ceremony',
		start: d(FRI, 18),
		end: d(FRI, 20),
		location: 'Friend Center',
		description: '',
		host: 'HackPrinceton',
		owner: '',
		category: 'academic',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'f10',
		name: 'Senior Bar Night',
		start: d(FRI, 22),
		end: d(FRI, 23, 59),
		location: 'Terrace Club',
		description: '',
		host: 'Senior Class',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},

	// ── Saturday ──
	{
		id: 'sa1',
		name: 'Late Night Pancakes',
		start: d(SAT, 0),
		end: d(SAT, 1),
		location: 'Frist Campus Center',
		description: '',
		host: 'Student Gov',
		owner: '',
		category: 'food',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'sa2',
		name: 'Morning Yoga',
		start: d(SAT, 8),
		end: d(SAT, 9),
		location: 'Dillon Gym',
		description: '',
		host: 'Athletics',
		owner: '',
		category: 'sports',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'sa3',
		name: 'Farmers Market',
		start: d(SAT, 9),
		end: d(SAT, 12),
		location: 'Palmer Square',
		description: '',
		host: 'Community',
		owner: '',
		category: 'food',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'sa4',
		name: 'Outdoor Climbing',
		start: d(SAT, 10),
		end: d(SAT, 13),
		location: 'Dillon Gym',
		description: '',
		host: 'Outdoor Club',
		owner: '',
		category: 'sports',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'sa5',
		name: 'Art Exhibition',
		start: d(SAT, 13),
		end: d(SAT, 17),
		location: 'Art Museum',
		description: '',
		host: 'Art Dept',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
	{
		id: 'sa6',
		name: 'Improv Show',
		start: d(SAT, 20),
		end: d(SAT, 22),
		location: 'Frist Theater',
		description: '',
		host: 'Improv Club',
		owner: '',
		category: 'social',
		from_mail: false,
		ordering: 0,
	},
];

// Light pastel bg, darker solid border/text color
export const CATEGORY_COLORS: Record<string, { bg: string; border: string }> = {
	sports: { bg: '#EFF6FF', border: '#3B82F6' },
	academic: { bg: '#F5F3FF', border: '#7C3AED' },
	food: { bg: '#FFF7ED', border: '#EA580C' },
	social: { bg: '#F0FDF4', border: '#16A34A' },
	default: { bg: '#F9FAFB', border: '#6B7280' },
};

export function getCategoryColor(category: string): { bg: string; border: string } {
	return CATEGORY_COLORS[category] ?? CATEGORY_COLORS.default;
}

type UseEventsResult = {
	events: CalendarEvent[];
	isLoading: boolean;
	error: string | null;
};

export function useEvents(startTime: Date, endTime: Date): UseEventsResult {
	const events = PLACEHOLDER_EVENTS.filter(
		(e) => new Date(e.start) <= endTime && new Date(e.end) >= startTime
	);
	return { events, isLoading: false, error: null };
}
